[scripts] yabai-float wip

diff --git a/bin/yabai-toggle-float b/bin/yabai-toggle-float
--- a/bin/yabai-toggle-float
+++ b/bin/yabai-toggle-float
@@ -1,4 +1,19 @@
 #!/usr/bin/env bash
 
-yabai -m window --toggle float
-yabai -m window --grid 4:5:1:0:3:4
+progname="$(basename "$0")"
+cmd="${1:-toggle}"
+
+case "$cmd" in
+    toggle)
+        yabai -m window --toggle float
+        yabai -m window --grid 4:5:1:0:3:4
+    ;;
+    on)
+    ;;
+    off)
+    ;;
+    *)
+        echo "${progname}: Invalid subcommand '$1'" >&2
+        exit 1
+    ;;
+esac
